import { Metadata } from "next";
import { ReactNode } from "react";
import Navbar from "./_components/Header/Navbar";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "كــاشو - نظم بيعك أونلاين بسهولة",
  description: "Generated by create next app",
};
export default async function DashboardLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-5 md:px-6 lg:px-8">
      <Navbar />
      <main className=" relative">{children}</main>
      <Footer />
    </div>
  );
}
