// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore

// ! Author : Maro Asam

import "./globals.css";
import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/theme/theme-provider";

const cairoFont = Cairo({
  subsets: ["arabic"],
  variable: "--font-cairo",
});

export const metadata: Metadata = {
  title: "كـــاشو",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={cn(cairoFont.className)}
      suppressHydrationWarning
    >
      <body
        className={`antialiased mx-auto `}
        cz-shortcut-listen="true"
        smooth-scroll="true"
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main>
            <NextTopLoader />

            {children}
            <Toaster theme="light" dir="rtl" richColors position="top-center" />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
