import "./globals.css";
import type { Metadata } from "next";
import { Cairo, Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "كـــاشو",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={cn("font-sans", inter.variable)}
      style={{ scrollBehavior: "smooth" }}
    >
      <body
        className={` antialiased  mx-auto`}
        cz-shortcut-listen="true"
        smooth-scroll="true"
      >
        <main>
          <NextTopLoader />

          {children}
          <Toaster theme="light" dir="rtl" richColors position="top-center" />
        </main>
      </body>
    </html>
  );
}
