/* eslint-disable @next/next/no-page-custom-font */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore

// ! Author : Maro Asam

import "./globals.css";
import type { Metadata } from "next";
import { Cairo, Geist, Manrope } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";
import { cn } from "@/lib/utils";

const manrope = Manrope({subsets:['latin'],variable:'--font-sans'});

const cairoFont = Cairo({
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "كـــاشو",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className={cn(cairoFont.className, "font-sans", manrope.variable)}>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Alyamama:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`antialiased mx-auto `}
        cz-shortcut-listen="true"
        smooth-scroll="true"
      >
        <main>
          <NextTopLoader />

          {children}
          <Toaster theme="light" dir="rtl" richColors position="top-center" />
        </main>
      </body>
    </html>
  );
}
