import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "كــاشو - انشاء وتسجيل حساب جديد",
  description: "Generated by create next app",
};
export default async function AuthLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <div className="mx-auto">
      <main className=" relative">{children}</main>
    </div>
  );
}
