import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default async function DashboardLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <div className="max-w-screen-2xl mx-auto">
      <main className="px-4 sm:px-5 md:px-6 lg:px-8">{children}</main>
    </div>
  );
}
